# Generated by Django 3.1.5 on 2021-08-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_ID', models.TextField()),
                ('Image_file', models.ImageField(upload_to='')),
                ('Question_type', models.TextField()),
                ('Questio_text', models.TextField()),
                ('Option_A', models.TextField()),
                ('Option_B', models.TextField()),
                ('Option_C', models.TextField()),
                ('Option_D', models.TextField()),
                ('Answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
