# Generated by Django 3.1.5 on 2021-08-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_ID', models.TextField()),
                ('Image_file', models.ImageField(blank=True, upload_to='images/')),
                ('Question_type', models.TextField()),
                ('Questio_text', models.TextField()),
                ('Option_A', models.TextField(blank=True)),
                ('Option_B', models.TextField(blank=True)),
                ('Option_C', models.TextField(blank=True)),
                ('Option_D', models.TextField(blank=True)),
                ('Answer', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
