# Generated by Django 3.1.5 on 2021-08-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210802_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Option_A',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_B',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_C',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_D',
            field=models.TextField(blank=True, null=True),
        ),
    ]
