# Generated by Django 3.1.5 on 2021-08-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210802_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Image_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
