# Generated by Django 3.1.5 on 2021-08-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210802_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='result',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='time_history',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
