# Generated by Django 3.1.5 on 2021-08-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210802_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
